### ISSUE TITLE
Write Mode Error

### ISSUE THREAD

**Issue by Getty-13** [BernardZhao/gltch#3]
I am trying to run the program through the docker-compose, which built itself correctly, but keeps returning this error:

Generating image face mask...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 629, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/lenssort/lenssort/__main__.py", line 30, in <module>
    result.save(output_path)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2240, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 631, in _save
    raise OSError(f"cannot write mode {im.mode} as JPEG") from e
OSError: cannot write mode RGBA as JPEG
ERROR: 1

How should I get around the RGBA error?

**Comment by j-getman** [comment]
I was not saving the output as a png
